workflows:
    version: 2
    build-and-test:
        jobs:
        - build

version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.9
            environment:
                FLASK_CONFIG: testing
                TEST_DATABASE_URL:  DATABASE_URL=postgresql://myUsr:somePwd@localhost:5432/myUsr
            - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: "somePwd"
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
            - run:
                name: Install Python deps
                command: |
                    pip install -r requirements/dev.txt
                    flask db migrate
                    flask db upgrade
                    flask test
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
                paths:
                - "venv"
