workflows:
    version: 2
    build-and-test:
        jobs:
        - build and initialise
        - deploy:
            requires:
                - build and initialise
        - dockerB&P:
            requires:
                - deploy

version: 2
jobs:
    build and initialise:
        docker:
          - image: circleci/python:3.6.9
            environment:
                DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/flask_db_test
          - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: somePwd
        steps:
          - checkout   
          - run:
              name: Install Python deps and initialise flask 
              command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements/dev.txt 
                  flask db upgrade    
                  flask test

    dockerB&P:
        docker:
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build application Docker image
                command: docker build --cache-from=app -t app .
            - deploy:
                name: push app to dockerhub
                command: |
                    docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
                    docker tag app $DOCKER_HUB_USER_ID/my-python-app:$CIRCLE_BUILD_NUM
                    docker tag app $DOCKER_HUB_USER_ID/my-python-app:latest
                    docker push $DOCKER_HUB_USER_ID/my-python-app:$CIRCLE_BUILD_NUM
                    docker push $DOCKER_HUB_USER_ID/my-python-app:latest

    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
          - checkout
          - run:
              name: Deploy Master to Heroku
              command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master