workflows:
    version: 2
    build-and-test:
        jobs:
        - build

version: 2
jobs:
    build:
        docker:
          - image: circleci/python:3.6.9
          - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: somePwd
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
            - run:
                name: Install Python db
                command: |
                    pip install -r requirements/dev.txt --user
                    flask db migrate
                    flask db upgrade
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
                paths:
                - ./venv
