workflows:
    version: 2
    build-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
  
  version: 2
  jobs:
    build:
      docker:
        - image: circleci/python:3.6.9-stretch-browsers
          environment:
            FLASK_CONFIG: testing
            TEST_DATABASE_URL:  DATABASE_URL=postgresql://myUsr:somePwd@localhost:5432/myUsr
        - image: circleci/postgres:9.6.5-alpine-ram
          environment:
            POSTGRES_USER: myUsr
            POSTGRES_DB: flask_db_test
            POSTGRES_PASSWORD: "somePwd"
      steps:
        - checkout
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
        - run:
            name: Install Python deps in a venv
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements/dev.txt
        - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
            paths:
              - "venv"
        - run:
            command: |
              . venv/bin/activate
              python manage.py test
        - store_artifacts:
            path: test-reports/
            destination: tr1
        - store_test_results:
            path: test-reports/