workflows:
    version: 2
    build-and-test:
        jobs:
        - build and initialise

version: 2
jobs:
    build and initialise:
        docker:
          - image: circleci/python:3.6.9
            environment:
                DATABASE_URL: postgresql://myUser:somePwd@localhost:5432/flask_db_test
          - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: somePwd
        steps:
          - run:
              name: Install Python deps in a venv
              command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements/dev.txt 
                  flask db upgrade    
                  flask test

