workflows:
    version: 2
    build-and-test:
        jobs:
        - build

version: 2
jobs:
    build:
        docker:
          - image: circleci/python:3.6.9
          - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: somePwd
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    - v1-dependencies-
            - run:
                name: Install Python db
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    flask db migrate
                    flask db upgrade
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                - ./venv
