workflows:
    version: 2
    build-and-test:
        jobs:
        - build

version: 2
jobs:
    build:
        docker:
          - image: circleci/python:3.6.4
          - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: somePwd
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements/dev.txt" }}
            - run:
                name: Install Python deps in a venv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements/dev.txt
                    flask db upgrade    
                    flask db test
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
                paths:
                - "venv"
