workflows:
    version: 2
    build-and-test:
        jobs:
        - build and initialise
        - deploy 

version: 2
jobs:
    build and initialise:
        docker:
          - image: circleci/python:3.6.9
            environment:
                DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/flask_db_test
          - image: circleci/postgres:10.10
            environment:
                POSTGRES_USER: myUsr
                POSTGRES_DB: flask_db_test
                POSTGRES_PASSWORD: somePwd
        steps:
          - checkout   
          - run:
              name: Install Python deps and initialise flask 
              command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements/dev.txt 
                  flask db upgrade    
                  flask test
    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
          - checkout
          - run:
              name: Deploy Master to Heroku
              command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master